<Project>
  <PropertyGroup Condition="Exists('C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1')">
    <FrameworkPathOverride>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1</FrameworkPathOverride>
  </PropertyGroup>
</Project>
