namespace _DLC8
{
	public enum DLC8CommonEvent
	{
		SHOW_DIALOG_TIP = 0,
		SHOW_DIALOG = 1,
		START_DIALOG = 2,
		FINISH_DIALOG = 3,
		SHOW_CHAT = 4,
		START_CHAT = 5,
		SHOW_CLEAR_STAGE_BUTTON = 6,
		START_GAME = 7,
		OUT_OF_RESOURCES = 8,
		OUT_OF_LV = 9,
		FINISH_GAMME = 10,
		FIRST_FINISH_GAME = 11,
		UNLOCK_MAP = 12,
		UNLOCK_LEVEL = 13,
		UNLOCK_APP = 14,
		CLOSE_CONTENT = 15,
		SHOW_WARNING = 16,
		AUTO_SAVE = 17,
		SHOW_TEACHING = 18,
		CLOSE_PRINT_CANVAS = 19,
		CHANGE_PRINT_PREFAB = 20,
		DOWNLOAD_PRINT_PREFAB = 21,
		ALL_SHOW = 22,
		ALL_HIDE = 23,
		SHOW_EMPLOYEE_BOOK = 24,
		CLOSE_CHAT = 25,
		PLAY_END_MOVIE = 26
	}
}
