namespace _DLC8
{
	public enum DLC8SpecialEvent
	{
		GUIDE_FIRST_SETP_COMPLETE = 0,
		GUIDE_COMPLETE = 1,
		STAGE_CLEAR = 2,
		STAGE_CLEAR_4000 = 3,
		ALUBA_HIGHEST = 4,
		ALUBA_LOWEST = 5,
		DANEL_LOWEST = 6,
		DDOS_40000 = 7,
		BASE_STATION_STAGE_CLEAR = 8,
		WATER_PIPE_STAGE_CLEAR = 9,
		VOICE_PRINT_STAGE_CLEAR = 10,
		VIRUS_STAGE_CLEAR = 11
	}
}
