namespace _DLC8.Main
{
	public enum TeachDialogStepType
	{
		UNSTART = 0,
		VIDEO_TIP = 1,
		VIDEO_TIP_FINISH = 2,
		UNLOCK_LEVEL = 3,
		UNLOCK_LEVEL_FINISH = 4,
		GAME_SUCCESS = 5,
		GAME_SUCCESS_FINISH = 6,
		WARNING = 7,
		WARNING_FINISH = 8,
		UNLOCK_PUBLICOPINION = 9,
		UNLOCK_PUBLICOPINION_FINISH = 10,
		UNLOCK_DOOS = 11,
		UNLOCK_DOOS_FINISH = 12,
		RANK = 13
	}
}
